/**
 * THIS FILE IS GENERATED by `gulp env` command from `env.json`
 * Generated on Fri Jan 27 2017 14:08:37 GMT-0800 (Pacific Standard Time)
 *
 * Make sure the keys in `env.model.ts` exist in `env.json`
 * otherwise it'll throw message like this
 * Property '<missing-key>' is missing in type '{}'
 *
 * Feel free to modify for direct updates in development
 * Missing this
 */
import { AppEnv } from './env.model';

export const ENV: AppEnv = {
};
//This needs to be updateded

